### PR TITLE
Pre-release Preview

### PR DESCRIPTION
**Pull request by lee-jongwoo**
All app features are finished.
Test the pre-release version and work on the landing page.

### CODE REVIEW

**Review by AppDevelopers2021 — APPROVED** [review]

**Comment by AppDevelopers2021** [comment]
OK, but we'll need to keep issue #5 in mind too.

**Comment by lee-jongwoo** [comment]
@AppDevelopers2021  Working on it!

**Comment by lee-jongwoo** [comment]
Fixed #5

**Review by AppDevelopers2021 — APPROVED** [review]
Ready for merge.

**Pull request merged**
